/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MuleGithubApp;

import java.util.ArrayList;
import java.util.List;

import org.junit.Test;

import mule.ci.tool.app.App;
import mule.ci.tool.app.util.AppException;
import mule.ci.tool.app.util.Const;

public class AppTest {

	@Test
	public void constInit() throws AppException {
		Const.init();
	}
	
//	@Test
	public void uploadApplicationFile() throws AppException {
		Const.PROJECT_HOME = "C:\\Users\\masaki.kawaguchi\\Documents\\MuleGithubApp\\app";
		Const.init();
//		Const.RELEASE_NAME = "account-0.0.1";
//		Const.BRANCH = "staging";
		App.uploadApplicationFile();
	}
	
//	@Test
	public void downloadApplicationFile() throws AppException {
		Const.init();
		App.downloadApplicationFile();
	}
	
//	@Test
	public void main() throws AppException {
		List<String> args = new ArrayList<>();
		args.add("-upload");
		args.add("-config");
		args.add("C:\\Users\\masaki.kawaguchi\\Documents\\MuleGithubApp\\app");
		String[] str = new String[args.size()];
		App.main(args.toArray(str));
	}
}
